//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 27-3-2020 10:37:53
namespace EFCoreSecurityODataConsoleClient
{
    /// <summary>
    /// There are no comments for DefaultContainer in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DefaultContainer")]
    public partial class DefaultContainer : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new DefaultContainer object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public DefaultContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "COS", "EFCoreSecurityODataConsoleClient");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("EFCoreSecurityODataConsoleClient", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("COS.", originalNameAttribute.OriginalName);
                }
                return string.Concat("COS.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Contact in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Contact")]
        public global::Microsoft.OData.Client.DataServiceQuery<ContactRecord> Contact
        {
            get
            {
                if ((this._Contact == null))
                {
                    this._Contact = base.CreateQuery<ContactRecord>("Contact");
                }
                return this._Contact;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<ContactRecord> _Contact;
        /// <summary>
        /// There are no comments for Contact in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToContact(ContactRecord contactRecord)
        {
            base.AddObject("Contact", contactRecord);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""COS"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""ContactRecord"">
        <Key>
          <PropertyRef Name=""Index"" />
        </Key>
        <Property Name=""Index"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""ArchivedDateTime"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""BillingAddressBlock"" Type=""Edm.String"" />
        <Property Name=""Email"" Type=""Edm.String"" />
        <Property Name=""EmailErrorCount"" Type=""Edm.Int32"" />
        <Property Name=""FormalName"" Type=""Edm.String"" />
        <Property Name=""HasDifferentPostalAddress"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""HasDifferentVisitingAddress"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""ImportDateTime"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Initials"" Type=""Edm.String"" />
        <Property Name=""IsArchived"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""IsDebtor"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""IsLegalEntity"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""JobTitle"" Type=""Edm.String"" />
        <Property Name=""LastModificationDateTime"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""LetterSalutation"" Type=""Edm.String"" />
        <Property Name=""LongName"" Type=""Edm.String"" />
        <Property Name=""MobileNo"" Type=""Edm.String"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""No"" Type=""Edm.String"" />
        <Property Name=""PostalAddressBlock"" Type=""Edm.String"" />
        <Property Name=""ShortName"" Type=""Edm.String"" />
        <Property Name=""TelNo"" Type=""Edm.String"" />
        <Property Name=""VisitingAddressBlock"" Type=""Edm.String"" />
      </EntityType>
      <EntityContainer Name=""DefaultContainer"">
        <EntitySet Name=""Contact"" EntityType=""COS.ContactRecord"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;
                    
                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for ContactRecordSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ContactRecordSingle")]
    public partial class ContactRecordSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ContactRecord>
    {
        /// <summary>
        /// Initialize a new ContactRecordSingle object.
        /// </summary>
        public ContactRecordSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ContactRecordSingle object.
        /// </summary>
        public ContactRecordSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ContactRecordSingle object.
        /// </summary>
        public ContactRecordSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ContactRecord> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for ContactRecord in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Index
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Index")]
    [global::Microsoft.OData.Client.EntitySet("Contact")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("ContactRecord")]
    public partial class ContactRecord : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ContactRecord object.
        /// </summary>
        /// <param name="index">Initial value of Index.</param>
        /// <param name="hasDifferentPostalAddress">Initial value of HasDifferentPostalAddress.</param>
        /// <param name="hasDifferentVisitingAddress">Initial value of HasDifferentVisitingAddress.</param>
        /// <param name="isArchived">Initial value of IsArchived.</param>
        /// <param name="isDebtor">Initial value of IsDebtor.</param>
        /// <param name="isLegalEntity">Initial value of IsLegalEntity.</param>
        /// <param name="lastModificationDateTime">Initial value of LastModificationDateTime.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static ContactRecord CreateContactRecord(int index, 
                    bool hasDifferentPostalAddress, 
                    bool hasDifferentVisitingAddress, 
                    bool isArchived, 
                    bool isDebtor, 
                    bool isLegalEntity, 
                    global::System.DateTimeOffset lastModificationDateTime)
        {
            ContactRecord contactRecord = new ContactRecord();
            contactRecord.Index = index;
            contactRecord.HasDifferentPostalAddress = hasDifferentPostalAddress;
            contactRecord.HasDifferentVisitingAddress = hasDifferentVisitingAddress;
            contactRecord.IsArchived = isArchived;
            contactRecord.IsDebtor = isDebtor;
            contactRecord.IsLegalEntity = isLegalEntity;
            contactRecord.LastModificationDateTime = lastModificationDateTime;
            return contactRecord;
        }
        /// <summary>
        /// There are no comments for Property Index in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Index")]
        public int Index
        {
            get
            {
                return this._Index;
            }
            set
            {
                this.OnIndexChanging(value);
                this._Index = value;
                this.OnIndexChanged();
                this.OnPropertyChanged("Index");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private int _Index;
        partial void OnIndexChanging(int value);
        partial void OnIndexChanged();
        /// <summary>
        /// There are no comments for Property ArchivedDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ArchivedDateTime")]
        public global::System.Nullable<global::System.DateTimeOffset> ArchivedDateTime
        {
            get
            {
                return this._ArchivedDateTime;
            }
            set
            {
                this.OnArchivedDateTimeChanging(value);
                this._ArchivedDateTime = value;
                this.OnArchivedDateTimeChanged();
                this.OnPropertyChanged("ArchivedDateTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<global::System.DateTimeOffset> _ArchivedDateTime;
        partial void OnArchivedDateTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnArchivedDateTimeChanged();
        /// <summary>
        /// There are no comments for Property BillingAddressBlock in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BillingAddressBlock")]
        public string BillingAddressBlock
        {
            get
            {
                return this._BillingAddressBlock;
            }
            set
            {
                this.OnBillingAddressBlockChanging(value);
                this._BillingAddressBlock = value;
                this.OnBillingAddressBlockChanged();
                this.OnPropertyChanged("BillingAddressBlock");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _BillingAddressBlock;
        partial void OnBillingAddressBlockChanging(string value);
        partial void OnBillingAddressBlockChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Email")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property EmailErrorCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EmailErrorCount")]
        public global::System.Nullable<int> EmailErrorCount
        {
            get
            {
                return this._EmailErrorCount;
            }
            set
            {
                this.OnEmailErrorCountChanging(value);
                this._EmailErrorCount = value;
                this.OnEmailErrorCountChanged();
                this.OnPropertyChanged("EmailErrorCount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _EmailErrorCount;
        partial void OnEmailErrorCountChanging(global::System.Nullable<int> value);
        partial void OnEmailErrorCountChanged();
        /// <summary>
        /// There are no comments for Property FormalName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FormalName")]
        public string FormalName
        {
            get
            {
                return this._FormalName;
            }
            set
            {
                this.OnFormalNameChanging(value);
                this._FormalName = value;
                this.OnFormalNameChanged();
                this.OnPropertyChanged("FormalName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _FormalName;
        partial void OnFormalNameChanging(string value);
        partial void OnFormalNameChanged();
        /// <summary>
        /// There are no comments for Property HasDifferentPostalAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HasDifferentPostalAddress")]
        public bool HasDifferentPostalAddress
        {
            get
            {
                return this._HasDifferentPostalAddress;
            }
            set
            {
                this.OnHasDifferentPostalAddressChanging(value);
                this._HasDifferentPostalAddress = value;
                this.OnHasDifferentPostalAddressChanged();
                this.OnPropertyChanged("HasDifferentPostalAddress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private bool _HasDifferentPostalAddress;
        partial void OnHasDifferentPostalAddressChanging(bool value);
        partial void OnHasDifferentPostalAddressChanged();
        /// <summary>
        /// There are no comments for Property HasDifferentVisitingAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HasDifferentVisitingAddress")]
        public bool HasDifferentVisitingAddress
        {
            get
            {
                return this._HasDifferentVisitingAddress;
            }
            set
            {
                this.OnHasDifferentVisitingAddressChanging(value);
                this._HasDifferentVisitingAddress = value;
                this.OnHasDifferentVisitingAddressChanged();
                this.OnPropertyChanged("HasDifferentVisitingAddress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private bool _HasDifferentVisitingAddress;
        partial void OnHasDifferentVisitingAddressChanging(bool value);
        partial void OnHasDifferentVisitingAddressChanged();
        /// <summary>
        /// There are no comments for Property ImportDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ImportDateTime")]
        public global::System.Nullable<global::System.DateTimeOffset> ImportDateTime
        {
            get
            {
                return this._ImportDateTime;
            }
            set
            {
                this.OnImportDateTimeChanging(value);
                this._ImportDateTime = value;
                this.OnImportDateTimeChanged();
                this.OnPropertyChanged("ImportDateTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<global::System.DateTimeOffset> _ImportDateTime;
        partial void OnImportDateTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnImportDateTimeChanged();
        /// <summary>
        /// There are no comments for Property Initials in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Initials")]
        public string Initials
        {
            get
            {
                return this._Initials;
            }
            set
            {
                this.OnInitialsChanging(value);
                this._Initials = value;
                this.OnInitialsChanged();
                this.OnPropertyChanged("Initials");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Initials;
        partial void OnInitialsChanging(string value);
        partial void OnInitialsChanged();
        /// <summary>
        /// There are no comments for Property IsArchived in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IsArchived")]
        public bool IsArchived
        {
            get
            {
                return this._IsArchived;
            }
            set
            {
                this.OnIsArchivedChanging(value);
                this._IsArchived = value;
                this.OnIsArchivedChanged();
                this.OnPropertyChanged("IsArchived");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private bool _IsArchived;
        partial void OnIsArchivedChanging(bool value);
        partial void OnIsArchivedChanged();
        /// <summary>
        /// There are no comments for Property IsDebtor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IsDebtor")]
        public bool IsDebtor
        {
            get
            {
                return this._IsDebtor;
            }
            set
            {
                this.OnIsDebtorChanging(value);
                this._IsDebtor = value;
                this.OnIsDebtorChanged();
                this.OnPropertyChanged("IsDebtor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private bool _IsDebtor;
        partial void OnIsDebtorChanging(bool value);
        partial void OnIsDebtorChanged();
        /// <summary>
        /// There are no comments for Property IsLegalEntity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IsLegalEntity")]
        public bool IsLegalEntity
        {
            get
            {
                return this._IsLegalEntity;
            }
            set
            {
                this.OnIsLegalEntityChanging(value);
                this._IsLegalEntity = value;
                this.OnIsLegalEntityChanged();
                this.OnPropertyChanged("IsLegalEntity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private bool _IsLegalEntity;
        partial void OnIsLegalEntityChanging(bool value);
        partial void OnIsLegalEntityChanged();
        /// <summary>
        /// There are no comments for Property JobTitle in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("JobTitle")]
        public string JobTitle
        {
            get
            {
                return this._JobTitle;
            }
            set
            {
                this.OnJobTitleChanging(value);
                this._JobTitle = value;
                this.OnJobTitleChanged();
                this.OnPropertyChanged("JobTitle");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _JobTitle;
        partial void OnJobTitleChanging(string value);
        partial void OnJobTitleChanged();
        /// <summary>
        /// There are no comments for Property LastModificationDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastModificationDateTime")]
        public global::System.DateTimeOffset LastModificationDateTime
        {
            get
            {
                return this._LastModificationDateTime;
            }
            set
            {
                this.OnLastModificationDateTimeChanging(value);
                this._LastModificationDateTime = value;
                this.OnLastModificationDateTimeChanged();
                this.OnPropertyChanged("LastModificationDateTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.DateTimeOffset _LastModificationDateTime;
        partial void OnLastModificationDateTimeChanging(global::System.DateTimeOffset value);
        partial void OnLastModificationDateTimeChanged();
        /// <summary>
        /// There are no comments for Property LetterSalutation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LetterSalutation")]
        public string LetterSalutation
        {
            get
            {
                return this._LetterSalutation;
            }
            set
            {
                this.OnLetterSalutationChanging(value);
                this._LetterSalutation = value;
                this.OnLetterSalutationChanged();
                this.OnPropertyChanged("LetterSalutation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _LetterSalutation;
        partial void OnLetterSalutationChanging(string value);
        partial void OnLetterSalutationChanged();
        /// <summary>
        /// There are no comments for Property LongName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LongName")]
        public string LongName
        {
            get
            {
                return this._LongName;
            }
            set
            {
                this.OnLongNameChanging(value);
                this._LongName = value;
                this.OnLongNameChanged();
                this.OnPropertyChanged("LongName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _LongName;
        partial void OnLongNameChanging(string value);
        partial void OnLongNameChanged();
        /// <summary>
        /// There are no comments for Property MobileNo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MobileNo")]
        public string MobileNo
        {
            get
            {
                return this._MobileNo;
            }
            set
            {
                this.OnMobileNoChanging(value);
                this._MobileNo = value;
                this.OnMobileNoChanged();
                this.OnPropertyChanged("MobileNo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _MobileNo;
        partial void OnMobileNoChanging(string value);
        partial void OnMobileNoChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("No")]
        public string No
        {
            get
            {
                return this._No;
            }
            set
            {
                this.OnNoChanging(value);
                this._No = value;
                this.OnNoChanged();
                this.OnPropertyChanged("No");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _No;
        partial void OnNoChanging(string value);
        partial void OnNoChanged();
        /// <summary>
        /// There are no comments for Property PostalAddressBlock in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PostalAddressBlock")]
        public string PostalAddressBlock
        {
            get
            {
                return this._PostalAddressBlock;
            }
            set
            {
                this.OnPostalAddressBlockChanging(value);
                this._PostalAddressBlock = value;
                this.OnPostalAddressBlockChanged();
                this.OnPropertyChanged("PostalAddressBlock");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _PostalAddressBlock;
        partial void OnPostalAddressBlockChanging(string value);
        partial void OnPostalAddressBlockChanged();
        /// <summary>
        /// There are no comments for Property ShortName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShortName")]
        public string ShortName
        {
            get
            {
                return this._ShortName;
            }
            set
            {
                this.OnShortNameChanging(value);
                this._ShortName = value;
                this.OnShortNameChanged();
                this.OnPropertyChanged("ShortName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _ShortName;
        partial void OnShortNameChanging(string value);
        partial void OnShortNameChanged();
        /// <summary>
        /// There are no comments for Property TelNo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TelNo")]
        public string TelNo
        {
            get
            {
                return this._TelNo;
            }
            set
            {
                this.OnTelNoChanging(value);
                this._TelNo = value;
                this.OnTelNoChanged();
                this.OnPropertyChanged("TelNo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _TelNo;
        partial void OnTelNoChanging(string value);
        partial void OnTelNoChanged();
        /// <summary>
        /// There are no comments for Property VisitingAddressBlock in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("VisitingAddressBlock")]
        public string VisitingAddressBlock
        {
            get
            {
                return this._VisitingAddressBlock;
            }
            set
            {
                this.OnVisitingAddressBlockChanging(value);
                this._VisitingAddressBlock = value;
                this.OnVisitingAddressBlockChanged();
                this.OnPropertyChanged("VisitingAddressBlock");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _VisitingAddressBlock;
        partial void OnVisitingAddressBlockChanging(string value);
        partial void OnVisitingAddressBlockChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::EFCoreSecurityODataConsoleClient.ContactRecord as global::EFCoreSecurityODataConsoleClient.ContactRecordSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::EFCoreSecurityODataConsoleClient.ContactRecordSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityODataConsoleClient.ContactRecord> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::EFCoreSecurityODataConsoleClient.ContactRecordSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EFCoreSecurityODataConsoleClient.ContactRecord as global::EFCoreSecurityODataConsoleClient.ContactRecordSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="index">The value of index</param>
        public static global::EFCoreSecurityODataConsoleClient.ContactRecordSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityODataConsoleClient.ContactRecord> source,
            int index)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Index", index }
            };
            return new global::EFCoreSecurityODataConsoleClient.ContactRecordSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
